### PR TITLE
Purged some `int`s for `uint8_t` when using the axis enum

### PR DESCRIPTION
**Pull request by gudnimg**
I tried to create only one commit but seems the rest of latest MK3 commits came too. Let me know if you'd like me to drop them.

I purged some `int` for `uint8_t` when using axis enum. Saving total of 76 bytes of flash. No change in SRAM.

### CODE REVIEW

**Comment by leptun** [comment]
Looking good. I’ll try merging Mk3 into my branch first to see if it fixes the extra commits.

**Comment by leptun** [comment]
@gudnimg Rebased the branch and now the extra commits are gone. Let me know when you want to merge

**Comment by gudnimg** [comment]
I think this is probably good for now. I've pushed most of the things I've noticed except about the variable `fanSpeed`, that one is a bit more pain to change imo.

Already 364 byte savings in this PR, it adds up quickly 😄

**Comment by gudnimg** [comment]
Damn I seem to have reverted your change in those lines [4] --> [1 + EXTRUDERS] I will try to fix it

**Comment by gudnimg** [comment]
Hi @leptun, may I ask to merge this PR when you have time? 🤓👍

**Review by leptun — APPROVED** [review]

**Pull request merged**
